# Generated by Django 4.1 on 2022-09-01 14:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_document_created_at_document_modified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='tag',
            field=models.CharField(default=django.utils.timezone.now, max_length=25),
            preserve_default=False,
        ),
    ]
