# Generated by Django 4.1 on 2022-09-01 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0009_remove_document_category_document_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='tag',
            new_name='category',
        ),
    ]
