# Generated by Django 4.1 on 2022-09-02 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0010_rename_tag_document_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='priority_read',
            field=models.CharField(choices=[('l', 'Low'), ('n', 'Neutral'), ('h', 'High')], default='l', max_length=8),
        ),
    ]
