# Generated by Django 4.1 on 2022-09-02 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0012_rename_priority_read_document_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='document',
            name='priority',
        ),
    ]
