# Generated by Django 4.1 on 2022-09-02 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0014_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='priority',
            field=models.CharField(choices=[('l', 'Low'), ('n', 'Neutral'), ('h', 'High')], default='low', max_length=7),
            preserve_default=False,
        ),
    ]
