# Generated by Django 4.1 on 2022-09-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0015_document_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='priority',
            field=models.CharField(max_length=7),
        ),
    ]
